### ISSUE TITLE
IP rotation mechanism doesn't works when target server is specified.

### ISSUE THREAD

**Issue by justnoxx** [olegwtf/p5-AnyEvent-Whois-Raw#3]
Seems like IP rotation mechanism doesn't works when whois sub called with specified server. This is a wrong behavior.

How can we fix that behavior, or what we should do?

**Comment by olegwtf** [comment]
Can you provide an example?

**Comment by olegwtf** [comment]
May be we should pass `$srv` to `_sock_prepare_cb` instead of `$dom` here https://metacpan.org/source/OLEG/AnyEvent-Whois-Raw-0.06/lib/AnyEvent/Whois/Raw.pm#L192 ?

**Comment by justnoxx** [comment]
Or we can perform a little refactoring of _sock_prepare_cb and change params to hash with these changes?

**Comment by olegwtf** [comment]
Does this looks good for you: 0db6177
BTW, looks like `Net::Whois::Raw` has same problem

**Comment by justnoxx** [comment]
Ok, thanks, that's good. I going to fix this issue in Net::Whois::Raw.

**Comment by olegwtf** [comment]
Released
